java -jar closure-compiler-v20200406.jar \
     --js node_modules/google-closure-library/closure/**.js \
     --js node_modules/google-closure-library/third_party/closure/**.js \
     --js soy-jssrc/**.js \
     --js protobuf-3.11.4/js/map.js \
     --js protobuf-3.11.4/js/message.js \
     --js protobuf-3.11.4/js/binary/**.js \
     --js proto/**.js \
     --js xid.js \
     --js simple.soy.js \
     --js hello.js \
     --entry_point=hello.js \
     --compilation_level ADVANCED_OPTIMIZATIONS
